[2024-04-25T03:59:21.578+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_mnist_784_data.obtain_original_data scheduled__2024-04-24T00:00:00+00:00 [queued]>
[2024-04-25T03:59:21.583+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_mnist_784_data.obtain_original_data scheduled__2024-04-24T00:00:00+00:00 [queued]>
[2024-04-25T03:59:21.583+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-25T03:59:21.593+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): obtain_original_data> on 2024-04-24 00:00:00+00:00
[2024-04-25T03:59:21.598+0000] {standard_task_runner.py:60} INFO - Started process 7947 to run task
[2024-04-25T03:59:21.602+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_mnist_784_data', 'obtain_original_data', 'scheduled__2024-04-24T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/etl_process.py', '--cfg-path', '/tmp/tmply2s58ao']
[2024-04-25T03:59:21.603+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask obtain_original_data
[2024-04-25T03:59:21.635+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_mnist_784_data.obtain_original_data scheduled__2024-04-24T00:00:00+00:00 [running]> on host b7ac1838226b
[2024-04-25T03:59:21.693+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Carlos Rodriguez' AIRFLOW_CTX_DAG_ID='process_etl_mnist_784_data' AIRFLOW_CTX_TASK_ID='obtain_original_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-24T00:00:00+00:00'
[2024-04-25T03:59:21.696+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvgi89lkzp --system-site-packages --python=python
[2024-04-25T03:59:21.703+0000] {process_utils.py:186} INFO - Output:
[2024-04-25T03:59:22.484+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 403ms
[2024-04-25T03:59:22.485+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvgi89lkzp, clear=False, no_vcs_ignore=False, global=True)
[2024-04-25T03:59:22.485+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-04-25T03:59:22.485+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-04-25T03:59:22.486+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-04-25T03:59:22.530+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvgi89lkzp/bin/pip install -r /tmp/venvgi89lkzp/requirements.txt
[2024-04-25T03:59:22.536+0000] {process_utils.py:186} INFO - Output:
[2024-04-25T03:59:24.451+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.6.0 (from -r /tmp/venvgi89lkzp/requirements.txt (line 1))
[2024-04-25T03:59:24.596+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.6.0-py3-none-any.whl.metadata (23 kB)
[2024-04-25T03:59:25.183+0000] {process_utils.py:190} INFO - Collecting ucimlrepo==0.0.3 (from -r /tmp/venvgi89lkzp/requirements.txt (line 2))
[2024-04-25T03:59:25.211+0000] {process_utils.py:190} INFO -   Downloading ucimlrepo-0.0.3-py3-none-any.whl.metadata (5.2 kB)
[2024-04-25T03:59:25.345+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvgi89lkzp/requirements.txt (line 1)) (1.34.88)
[2024-04-25T03:59:25.346+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvgi89lkzp/requirements.txt (line 1)) (1.34.88)
[2024-04-25T03:59:25.347+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvgi89lkzp/requirements.txt (line 1)) (1.24.4)
[2024-04-25T03:59:25.347+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvgi89lkzp/requirements.txt (line 1)) (23.2)
[2024-04-25T03:59:25.348+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvgi89lkzp/requirements.txt (line 1)) (2.0.3)
[2024-04-25T03:59:25.349+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=7.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvgi89lkzp/requirements.txt (line 1)) (14.0.2)
[2024-04-25T03:59:25.349+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvgi89lkzp/requirements.txt (line 1)) (4.9.0)
[2024-04-25T03:59:25.355+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venvgi89lkzp/requirements.txt (line 1)) (0.10.0)
[2024-04-25T03:59:25.356+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venvgi89lkzp/requirements.txt (line 1)) (0.10.1)
[2024-04-25T03:59:25.362+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvgi89lkzp/requirements.txt (line 1)) (2.8.2)
[2024-04-25T03:59:25.363+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvgi89lkzp/requirements.txt (line 1)) (1.26.18)
[2024-04-25T03:59:25.441+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venvgi89lkzp/requirements.txt (line 1)) (2023.3.post1)
[2024-04-25T03:59:25.442+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venvgi89lkzp/requirements.txt (line 1)) (2023.4)
[2024-04-25T03:59:25.449+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvgi89lkzp/requirements.txt (line 1)) (1.16.0)
[2024-04-25T03:59:25.494+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.6.0-py3-none-any.whl (403 kB)
[2024-04-25T03:59:25.775+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 403.8/403.8 kB 1.4 MB/s eta 0:00:00
[2024-04-25T03:59:25.798+0000] {process_utils.py:190} INFO - Downloading ucimlrepo-0.0.3-py3-none-any.whl (7.0 kB)
[2024-04-25T03:59:28.631+0000] {process_utils.py:190} INFO - Installing collected packages: ucimlrepo, awswrangler
[2024-04-25T03:59:29.008+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.6.0 ucimlrepo-0.0.3
[2024-04-25T03:59:29.146+0000] {process_utils.py:190} INFO - 
[2024-04-25T03:59:29.146+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.0
[2024-04-25T03:59:29.147+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-04-25T03:59:29.345+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvgi89lkzp/bin/python /tmp/venv-call52spo5zx/script.py /tmp/venv-call52spo5zx/script.in /tmp/venv-call52spo5zx/script.out /tmp/venv-call52spo5zx/string_args.txt /tmp/venv-call52spo5zx/termination.log
[2024-04-25T03:59:29.354+0000] {process_utils.py:186} INFO - Output:
[2024-04-25T03:59:34.608+0000] {process_utils.py:190} INFO - /home/***/.local/lib/python3.8/site-packages/sklearn/datasets/_openml.py:1022 FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
[2024-04-25T03:59:58.570+0000] {process_utils.py:190} INFO - [[34m2024-04-25T03:59:58.570+0000[0m] {[34mcredentials.py:[0m1147} INFO[0m - Found credentials in environment variables.[0m
[2024-04-25T03:59:59.655+0000] {process_utils.py:190} INFO - [[34m2024-04-25T03:59:59.654+0000[0m] {[34mconfigprovider.py:[0m957} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2024-04-25T04:00:06.774+0000] {process_utils.py:190} INFO - [[34m2024-04-25T04:00:06.773+0000[0m] {[34mconnectionpool.py:[0m323} WARNING[0m - Connection pool is full, discarding connection: s3. Connection pool size: 10[0m
[2024-04-25T04:00:06.796+0000] {process_utils.py:190} INFO - [[34m2024-04-25T04:00:06.774+0000[0m] {[34mconnectionpool.py:[0m323} WARNING[0m - Connection pool is full, discarding connection: s3. Connection pool size: 10[0m
[2024-04-25T04:00:21.824+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-04-25T04:00:21.832+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_mnist_784_data, task_id=obtain_original_data, execution_date=20240424T000000, start_date=20240425T035921, end_date=20240425T040021
[2024-04-25T04:00:21.856+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-25T04:00:21.870+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-25T19:59:30.632+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_mnist_784_data.obtain_original_data scheduled__2024-04-24T00:00:00+00:00 [queued]>
[2024-04-25T19:59:30.637+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_mnist_784_data.obtain_original_data scheduled__2024-04-24T00:00:00+00:00 [queued]>
[2024-04-25T19:59:30.637+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-25T19:59:30.646+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): obtain_original_data> on 2024-04-24 00:00:00+00:00
[2024-04-25T19:59:30.649+0000] {standard_task_runner.py:60} INFO - Started process 8322 to run task
[2024-04-25T19:59:30.651+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_mnist_784_data', 'obtain_original_data', 'scheduled__2024-04-24T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/etl_process.py', '--cfg-path', '/tmp/tmpmxlhib_3']
[2024-04-25T19:59:30.652+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask obtain_original_data
[2024-04-25T19:59:30.686+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_mnist_784_data.obtain_original_data scheduled__2024-04-24T00:00:00+00:00 [running]> on host fc2c8bd597e1
[2024-04-25T19:59:30.730+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Carlos Rodriguez' AIRFLOW_CTX_DAG_ID='process_etl_mnist_784_data' AIRFLOW_CTX_TASK_ID='obtain_original_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-24T00:00:00+00:00'
[2024-04-25T19:59:30.732+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvly3soez3 --system-site-packages --python=python
[2024-04-25T19:59:30.737+0000] {process_utils.py:186} INFO - Output:
[2024-04-25T19:59:31.592+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 444ms
[2024-04-25T19:59:31.593+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvly3soez3, clear=False, no_vcs_ignore=False, global=True)
[2024-04-25T19:59:31.593+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-04-25T19:59:31.593+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-04-25T19:59:31.594+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-04-25T19:59:31.633+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvly3soez3/bin/pip install -r /tmp/venvly3soez3/requirements.txt
[2024-04-25T19:59:31.638+0000] {process_utils.py:186} INFO - Output:
[2024-04-25T19:59:33.079+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.6.0 (from -r /tmp/venvly3soez3/requirements.txt (line 1))
[2024-04-25T19:59:33.196+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.6.0-py3-none-any.whl.metadata (23 kB)
[2024-04-25T19:59:33.925+0000] {process_utils.py:190} INFO - Collecting ucimlrepo==0.0.3 (from -r /tmp/venvly3soez3/requirements.txt (line 2))
[2024-04-25T19:59:33.948+0000] {process_utils.py:190} INFO -   Downloading ucimlrepo-0.0.3-py3-none-any.whl.metadata (5.2 kB)
[2024-04-25T19:59:33.996+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvly3soez3/requirements.txt (line 1)) (1.34.88)
[2024-04-25T19:59:33.997+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvly3soez3/requirements.txt (line 1)) (1.34.88)
[2024-04-25T19:59:33.998+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvly3soez3/requirements.txt (line 1)) (1.24.4)
[2024-04-25T19:59:33.998+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvly3soez3/requirements.txt (line 1)) (23.2)
[2024-04-25T19:59:34.001+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvly3soez3/requirements.txt (line 1)) (2.0.3)
[2024-04-25T19:59:34.001+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=7.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvly3soez3/requirements.txt (line 1)) (14.0.2)
[2024-04-25T19:59:34.002+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvly3soez3/requirements.txt (line 1)) (4.9.0)
[2024-04-25T19:59:34.007+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venvly3soez3/requirements.txt (line 1)) (0.10.0)
[2024-04-25T19:59:34.008+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venvly3soez3/requirements.txt (line 1)) (0.10.1)
[2024-04-25T19:59:34.014+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvly3soez3/requirements.txt (line 1)) (2.8.2)
[2024-04-25T19:59:34.016+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvly3soez3/requirements.txt (line 1)) (1.26.18)
[2024-04-25T19:59:34.097+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venvly3soez3/requirements.txt (line 1)) (2023.3.post1)
[2024-04-25T19:59:34.098+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venvly3soez3/requirements.txt (line 1)) (2023.4)
[2024-04-25T19:59:34.106+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvly3soez3/requirements.txt (line 1)) (1.16.0)
[2024-04-25T19:59:34.206+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.6.0-py3-none-any.whl (403 kB)
[2024-04-25T19:59:34.531+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 403.8/403.8 kB 1.2 MB/s eta 0:00:00
[2024-04-25T19:59:34.580+0000] {process_utils.py:190} INFO - Downloading ucimlrepo-0.0.3-py3-none-any.whl (7.0 kB)
[2024-04-25T19:59:36.960+0000] {process_utils.py:190} INFO - Installing collected packages: ucimlrepo, awswrangler
[2024-04-25T19:59:37.343+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.6.0 ucimlrepo-0.0.3
[2024-04-25T19:59:37.486+0000] {process_utils.py:190} INFO - 
[2024-04-25T19:59:37.487+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.0
[2024-04-25T19:59:37.487+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-04-25T19:59:37.663+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvly3soez3/bin/python /tmp/venv-calls2bt2mt0/script.py /tmp/venv-calls2bt2mt0/script.in /tmp/venv-calls2bt2mt0/script.out /tmp/venv-calls2bt2mt0/string_args.txt /tmp/venv-calls2bt2mt0/termination.log
[2024-04-25T19:59:37.667+0000] {process_utils.py:186} INFO - Output:
[2024-04-25T19:59:47.141+0000] {process_utils.py:190} INFO - /home/***/.local/lib/python3.8/site-packages/sklearn/datasets/_openml.py:1022 FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
[2024-04-25T20:00:14.464+0000] {process_utils.py:190} INFO - [[34m2024-04-25T20:00:14.463+0000[0m] {[34mcredentials.py:[0m1147} INFO[0m - Found credentials in environment variables.[0m
[2024-04-25T20:00:14.603+0000] {process_utils.py:190} INFO - [[34m2024-04-25T20:00:14.602+0000[0m] {[34mconfigprovider.py:[0m957} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2024-04-25T20:00:37.123+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-04-25T20:00:37.132+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_mnist_784_data, task_id=obtain_original_data, execution_date=20240424T000000, start_date=20240425T195930, end_date=20240425T200037
[2024-04-25T20:00:37.160+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-25T20:00:37.172+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-25T20:31:59.034+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_mnist_784_data.obtain_original_data scheduled__2024-04-24T00:00:00+00:00 [queued]>
[2024-04-25T20:31:59.038+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_mnist_784_data.obtain_original_data scheduled__2024-04-24T00:00:00+00:00 [queued]>
[2024-04-25T20:31:59.039+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-25T20:31:59.046+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): obtain_original_data> on 2024-04-24 00:00:00+00:00
[2024-04-25T20:31:59.049+0000] {standard_task_runner.py:60} INFO - Started process 3737 to run task
[2024-04-25T20:31:59.052+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_mnist_784_data', 'obtain_original_data', 'scheduled__2024-04-24T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/etl_process.py', '--cfg-path', '/tmp/tmplrn9dtca']
[2024-04-25T20:31:59.054+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask obtain_original_data
[2024-04-25T20:31:59.088+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_mnist_784_data.obtain_original_data scheduled__2024-04-24T00:00:00+00:00 [running]> on host b1d103f3af44
[2024-04-25T20:31:59.132+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Carlos Rodriguez' AIRFLOW_CTX_DAG_ID='process_etl_mnist_784_data' AIRFLOW_CTX_TASK_ID='obtain_original_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-24T00:00:00+00:00'
[2024-04-25T20:31:59.135+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv8xumludp --system-site-packages --python=python
[2024-04-25T20:31:59.141+0000] {process_utils.py:186} INFO - Output:
[2024-04-25T20:31:59.895+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 398ms
[2024-04-25T20:31:59.896+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venv8xumludp, clear=False, no_vcs_ignore=False, global=True)
[2024-04-25T20:31:59.896+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-04-25T20:31:59.897+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-04-25T20:31:59.897+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-04-25T20:31:59.969+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv8xumludp/bin/pip install -r /tmp/venv8xumludp/requirements.txt
[2024-04-25T20:31:59.975+0000] {process_utils.py:186} INFO - Output:
[2024-04-25T20:32:01.276+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.6.0 (from -r /tmp/venv8xumludp/requirements.txt (line 1))
[2024-04-25T20:32:01.409+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.6.0-py3-none-any.whl.metadata (23 kB)
[2024-04-25T20:32:01.601+0000] {process_utils.py:190} INFO - Collecting ucimlrepo==0.0.3 (from -r /tmp/venv8xumludp/requirements.txt (line 2))
[2024-04-25T20:32:01.628+0000] {process_utils.py:190} INFO -   Downloading ucimlrepo-0.0.3-py3-none-any.whl.metadata (5.2 kB)
[2024-04-25T20:32:01.693+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venv8xumludp/requirements.txt (line 1)) (1.34.88)
[2024-04-25T20:32:01.694+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venv8xumludp/requirements.txt (line 1)) (1.34.88)
[2024-04-25T20:32:01.695+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venv8xumludp/requirements.txt (line 1)) (1.24.4)
[2024-04-25T20:32:01.696+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venv8xumludp/requirements.txt (line 1)) (23.2)
[2024-04-25T20:32:01.698+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venv8xumludp/requirements.txt (line 1)) (2.0.3)
[2024-04-25T20:32:01.699+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=7.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venv8xumludp/requirements.txt (line 1)) (14.0.2)
[2024-04-25T20:32:01.699+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venv8xumludp/requirements.txt (line 1)) (4.9.0)
[2024-04-25T20:32:01.709+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venv8xumludp/requirements.txt (line 1)) (0.10.0)
[2024-04-25T20:32:01.710+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venv8xumludp/requirements.txt (line 1)) (0.10.1)
[2024-04-25T20:32:01.720+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venv8xumludp/requirements.txt (line 1)) (2.8.2)
[2024-04-25T20:32:01.721+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venv8xumludp/requirements.txt (line 1)) (1.26.18)
[2024-04-25T20:32:01.827+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venv8xumludp/requirements.txt (line 1)) (2023.3.post1)
[2024-04-25T20:32:01.828+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venv8xumludp/requirements.txt (line 1)) (2023.4)
[2024-04-25T20:32:01.836+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venv8xumludp/requirements.txt (line 1)) (1.16.0)
[2024-04-25T20:32:01.880+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.6.0-py3-none-any.whl (403 kB)
[2024-04-25T20:32:02.185+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 403.8/403.8 kB 1.3 MB/s eta 0:00:00
[2024-04-25T20:32:02.246+0000] {process_utils.py:190} INFO - Downloading ucimlrepo-0.0.3-py3-none-any.whl (7.0 kB)
[2024-04-25T20:32:04.887+0000] {process_utils.py:190} INFO - Installing collected packages: ucimlrepo, awswrangler
[2024-04-25T20:32:05.075+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.6.0 ucimlrepo-0.0.3
[2024-04-25T20:32:05.228+0000] {process_utils.py:190} INFO - 
[2024-04-25T20:32:05.229+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.0
[2024-04-25T20:32:05.229+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-04-25T20:32:05.398+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv8xumludp/bin/python /tmp/venv-call3gn_ep25/script.py /tmp/venv-call3gn_ep25/script.in /tmp/venv-call3gn_ep25/script.out /tmp/venv-call3gn_ep25/string_args.txt /tmp/venv-call3gn_ep25/termination.log
[2024-04-25T20:32:05.404+0000] {process_utils.py:186} INFO - Output:
[2024-04-25T20:32:10.272+0000] {process_utils.py:190} INFO - /home/***/.local/lib/python3.8/site-packages/sklearn/datasets/_openml.py:1022 FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
[2024-04-25T20:32:35.523+0000] {process_utils.py:190} INFO - [[34m2024-04-25T20:32:35.522+0000[0m] {[34mcredentials.py:[0m1147} INFO[0m - Found credentials in environment variables.[0m
[2024-04-25T20:32:35.695+0000] {process_utils.py:190} INFO - [[34m2024-04-25T20:32:35.695+0000[0m] {[34mconfigprovider.py:[0m957} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2024-04-25T20:33:32.044+0000] {process_utils.py:190} INFO - [[34m2024-04-25T20:33:32.044+0000[0m] {[34mconnectionpool.py:[0m323} WARNING[0m - Connection pool is full, discarding connection: s3. Connection pool size: 10[0m
[2024-04-25T20:33:32.045+0000] {process_utils.py:190} INFO - [[34m2024-04-25T20:33:32.044+0000[0m] {[34mconnectionpool.py:[0m323} WARNING[0m - Connection pool is full, discarding connection: s3. Connection pool size: 10[0m
[2024-04-25T20:33:32.429+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-04-25T20:33:32.438+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_mnist_784_data, task_id=obtain_original_data, execution_date=20240424T000000, start_date=20240425T203159, end_date=20240425T203332
[2024-04-25T20:33:32.461+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-25T20:33:32.474+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
