[2024-04-22T00:00:01.619+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: retrain_the_model.train_the_challenger_model scheduled__2024-04-21T00:00:00+00:00 [queued]>
[2024-04-22T00:00:01.624+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: retrain_the_model.train_the_challenger_model scheduled__2024-04-21T00:00:00+00:00 [queued]>
[2024-04-22T00:00:01.624+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-22T00:00:01.799+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_the_challenger_model> on 2024-04-21 00:00:00+00:00
[2024-04-22T00:00:01.803+0000] {standard_task_runner.py:60} INFO - Started process 3236 to run task
[2024-04-22T00:00:01.805+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'retrain_the_model', 'train_the_challenger_model', 'scheduled__2024-04-21T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/retrain_the_model.py', '--cfg-path', '/tmp/tmpenltv6f7']
[2024-04-22T00:00:01.807+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask train_the_challenger_model
[2024-04-22T00:00:01.994+0000] {task_command.py:423} INFO - Running <TaskInstance: retrain_the_model.train_the_challenger_model scheduled__2024-04-21T00:00:00+00:00 [running]> on host 3ab9e2e1209e
[2024-04-22T00:00:02.053+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Facundo Adrian Lucianna' AIRFLOW_CTX_DAG_ID='retrain_the_model' AIRFLOW_CTX_TASK_ID='train_the_challenger_model' AIRFLOW_CTX_EXECUTION_DATE='2024-04-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-21T00:00:00+00:00'
[2024-04-22T00:00:02.055+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvps_stcdy --system-site-packages --python=python
[2024-04-22T00:00:02.061+0000] {process_utils.py:186} INFO - Output:
[2024-04-22T00:00:02.978+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 466ms
[2024-04-22T00:00:02.978+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvps_stcdy, clear=False, no_vcs_ignore=False, global=True)
[2024-04-22T00:00:02.979+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-04-22T00:00:02.979+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-04-22T00:00:02.980+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-04-22T00:00:03.019+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvps_stcdy/bin/pip install -r /tmp/venvps_stcdy/requirements.txt
[2024-04-22T00:00:03.029+0000] {process_utils.py:186} INFO - Output:
[2024-04-22T00:00:05.150+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.6.0 (from -r /tmp/venvps_stcdy/requirements.txt (line 1))
[2024-04-22T00:00:05.261+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.6.0-py3-none-any.whl.metadata (23 kB)
[2024-04-22T00:00:05.980+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venvps_stcdy/requirements.txt (line 2))
[2024-04-22T00:00:06.000+0000] {process_utils.py:190} INFO -   Downloading mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-04-22T00:00:06.183+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvps_stcdy/requirements.txt (line 3)) (1.3.2)
[2024-04-22T00:00:06.226+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvps_stcdy/requirements.txt (line 1)) (1.34.88)
[2024-04-22T00:00:06.226+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvps_stcdy/requirements.txt (line 1)) (1.34.88)
[2024-04-22T00:00:06.228+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvps_stcdy/requirements.txt (line 1)) (1.24.4)
[2024-04-22T00:00:06.229+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvps_stcdy/requirements.txt (line 1)) (23.2)
[2024-04-22T00:00:06.232+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvps_stcdy/requirements.txt (line 1)) (2.0.3)
[2024-04-22T00:00:06.233+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=7.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvps_stcdy/requirements.txt (line 1)) (14.0.2)
[2024-04-22T00:00:06.234+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvps_stcdy/requirements.txt (line 1)) (4.9.0)
[2024-04-22T00:00:06.285+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (8.1.7)
[2024-04-22T00:00:06.286+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (3.0.0)
[2024-04-22T00:00:06.286+0000] {process_utils.py:190} INFO - Requirement already satisfied: entrypoints<1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (0.4)
[2024-04-22T00:00:06.287+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (3.1.43)
[2024-04-22T00:00:06.288+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (6.0.1)
[2024-04-22T00:00:06.288+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (4.25.2)
[2024-04-22T00:00:06.290+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (2023.3.post1)
[2024-04-22T00:00:06.290+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (2.31.0)
[2024-04-22T00:00:06.292+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (6.11.0)
[2024-04-22T00:00:06.292+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (0.4.4)
[2024-04-22T00:00:06.293+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (1.13.1)
[2024-04-22T00:00:06.294+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (7.0.0)
[2024-04-22T00:00:06.294+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (2.2.5)
[2024-04-22T00:00:06.295+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (1.10.1)
[2024-04-22T00:00:06.296+0000] {process_utils.py:190} INFO - Requirement already satisfied: querystring-parser<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (1.2.4)
[2024-04-22T00:00:06.296+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (1.4.51)
[2024-04-22T00:00:06.297+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (3.5.2)
[2024-04-22T00:00:06.297+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (3.7.5)
[2024-04-22T00:00:06.298+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (21.2.0)
[2024-04-22T00:00:06.299+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (3.1.3)
[2024-04-22T00:00:06.335+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvps_stcdy/requirements.txt (line 3)) (1.4.0)
[2024-04-22T00:00:06.336+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvps_stcdy/requirements.txt (line 3)) (3.4.0)
[2024-04-22T00:00:06.358+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (1.3.0)
[2024-04-22T00:00:06.359+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (5.13.0)
[2024-04-22T00:00:06.363+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venvps_stcdy/requirements.txt (line 1)) (0.10.0)
[2024-04-22T00:00:06.364+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venvps_stcdy/requirements.txt (line 1)) (0.10.1)
[2024-04-22T00:00:06.371+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvps_stcdy/requirements.txt (line 1)) (2.8.2)
[2024-04-22T00:00:06.372+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvps_stcdy/requirements.txt (line 1)) (1.26.18)
[2024-04-22T00:00:06.428+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (2.2.3)
[2024-04-22T00:00:06.430+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (2.1.2)
[2024-04-22T00:00:06.449+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (4.0.11)
[2024-04-22T00:00:06.531+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (3.17.0)
[2024-04-22T00:00:06.536+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (2.1.3)
[2024-04-22T00:00:06.566+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (1.1.1)
[2024-04-22T00:00:06.567+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (0.12.1)
[2024-04-22T00:00:06.568+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (4.51.0)
[2024-04-22T00:00:06.568+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (1.4.5)
[2024-04-22T00:00:06.570+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (10.3.0)
[2024-04-22T00:00:06.570+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (3.1.1)
[2024-04-22T00:00:06.656+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venvps_stcdy/requirements.txt (line 1)) (2023.4)
[2024-04-22T00:00:06.677+0000] {process_utils.py:190} INFO - Requirement already satisfied: six in /home/***/.local/lib/python3.8/site-packages (from querystring-parser<2->mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (1.16.0)
[2024-04-22T00:00:06.688+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (3.3.2)
[2024-04-22T00:00:06.689+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (3.6)
[2024-04-22T00:00:06.690+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (2023.11.17)
[2024-04-22T00:00:06.771+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (3.0.3)
[2024-04-22T00:00:06.930+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvps_stcdy/requirements.txt (line 2)) (5.0.1)
[2024-04-22T00:00:07.284+0000] {process_utils.py:190} INFO - Using cached awswrangler-3.6.0-py3-none-any.whl (403 kB)
[2024-04-22T00:00:07.303+0000] {process_utils.py:190} INFO - Downloading mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-04-22T00:00:12.991+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.5/19.5 MB 2.3 MB/s eta 0:00:00
[2024-04-22T00:00:15.007+0000] {process_utils.py:190} INFO - Installing collected packages: mlflow, awswrangler
[2024-04-22T00:00:15.007+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-04-22T00:00:15.009+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.12.1
[2024-04-22T00:00:15.009+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvps_stcdy
[2024-04-22T00:00:15.010+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-04-22T00:00:16.301+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.6.0 mlflow-2.10.2
[2024-04-22T00:00:16.425+0000] {process_utils.py:190} INFO - 
[2024-04-22T00:00:16.426+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.0
[2024-04-22T00:00:16.426+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-04-22T00:00:16.527+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvps_stcdy/bin/python /tmp/venv-call0hcrku47/script.py /tmp/venv-call0hcrku47/script.in /tmp/venv-call0hcrku47/script.out /tmp/venv-call0hcrku47/string_args.txt /tmp/venv-call0hcrku47/termination.log
[2024-04-22T00:00:16.533+0000] {process_utils.py:186} INFO - Output:
[2024-04-22T00:00:20.092+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-04-22T00:00:20.092+0000] {process_utils.py:190} INFO -   File "/tmp/venv-call0hcrku47/script.py", line 132, in <module>
[2024-04-22T00:00:20.092+0000] {process_utils.py:190} INFO -     res = train_the_challenger_model(*arg_dict["args"], **arg_dict["kwargs"])
[2024-04-22T00:00:20.093+0000] {process_utils.py:190} INFO -   File "/tmp/venv-call0hcrku47/script.py", line 110, in train_the_challenger_model
[2024-04-22T00:00:20.093+0000] {process_utils.py:190} INFO -     champion_model = load_the_champion_model()
[2024-04-22T00:00:20.093+0000] {process_utils.py:190} INFO -   File "/tmp/venv-call0hcrku47/script.py", line 42, in load_the_champion_model
[2024-04-22T00:00:20.093+0000] {process_utils.py:190} INFO -     model_data = client.get_model_version_by_alias(model_name, alias)
[2024-04-22T00:00:20.094+0000] {process_utils.py:190} INFO -   File "/tmp/venvps_stcdy/lib/python3.8/site-packages/mlflow/tracking/client.py", line 3745, in get_model_version_by_alias
[2024-04-22T00:00:20.094+0000] {process_utils.py:190} INFO -     return self._get_registry_client().get_model_version_by_alias(name, alias)
[2024-04-22T00:00:20.094+0000] {process_utils.py:190} INFO -   File "/tmp/venvps_stcdy/lib/python3.8/site-packages/mlflow/tracking/_model_registry/client.py", line 366, in get_model_version_by_alias
[2024-04-22T00:00:20.094+0000] {process_utils.py:190} INFO -     return self.store.get_model_version_by_alias(name, alias)
[2024-04-22T00:00:20.094+0000] {process_utils.py:190} INFO -   File "/tmp/venvps_stcdy/lib/python3.8/site-packages/mlflow/store/model_registry/rest_store.py", line 400, in get_model_version_by_alias
[2024-04-22T00:00:20.095+0000] {process_utils.py:190} INFO -     response_proto = self._call_endpoint(GetModelVersionByAlias, req_body)
[2024-04-22T00:00:20.095+0000] {process_utils.py:190} INFO -   File "/tmp/venvps_stcdy/lib/python3.8/site-packages/mlflow/store/model_registry/base_rest_store.py", line 44, in _call_endpoint
[2024-04-22T00:00:20.095+0000] {process_utils.py:190} INFO -     return call_endpoint(
[2024-04-22T00:00:20.095+0000] {process_utils.py:190} INFO -   File "/tmp/venvps_stcdy/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 220, in call_endpoint
[2024-04-22T00:00:20.095+0000] {process_utils.py:190} INFO -     response = verify_rest_response(response, endpoint)
[2024-04-22T00:00:20.096+0000] {process_utils.py:190} INFO -   File "/tmp/venvps_stcdy/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 152, in verify_rest_response
[2024-04-22T00:00:20.096+0000] {process_utils.py:190} INFO -     raise RestException(json.loads(response.text))
[2024-04-22T00:00:20.096+0000] {process_utils.py:190} INFO - mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Registered model alias champion not found.
[2024-04-22T00:00:20.808+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
INVALID_PARAMETER_VALUE: Registered model alias champion not found.
[2024-04-22T00:00:20.811+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=retrain_the_model, task_id=train_the_challenger_model, execution_date=20240421T000000, start_date=20240422T000001, end_date=20240422T000020
[2024-04-22T00:00:20.820+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 16 for task train_the_challenger_model (Process returned non-zero exit status 1.
INVALID_PARAMETER_VALUE: Registered model alias champion not found.; 3236)
[2024-04-22T00:00:20.846+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-22T00:00:20.861+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
