[2024-04-21T22:57:02.527+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_heart_data.obtain_original_data manual__2024-04-21T22:57:01.536063+00:00 [queued]>
[2024-04-21T22:57:02.531+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_heart_data.obtain_original_data manual__2024-04-21T22:57:01.536063+00:00 [queued]>
[2024-04-21T22:57:02.532+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-21T22:57:02.540+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): obtain_original_data> on 2024-04-21 22:57:01.536063+00:00
[2024-04-21T22:57:02.545+0000] {standard_task_runner.py:60} INFO - Started process 16742 to run task
[2024-04-21T22:57:02.548+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_heart_data', 'obtain_original_data', 'manual__2024-04-21T22:57:01.536063+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/etl_process.py', '--cfg-path', '/tmp/tmp5umbgswo']
[2024-04-21T22:57:02.551+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask obtain_original_data
[2024-04-21T22:57:02.588+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_heart_data.obtain_original_data manual__2024-04-21T22:57:01.536063+00:00 [running]> on host 2e52d55d127b
[2024-04-21T22:57:02.650+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Facundo Adrian Lucianna' AIRFLOW_CTX_DAG_ID='process_etl_heart_data' AIRFLOW_CTX_TASK_ID='obtain_original_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-21T22:57:01.536063+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-21T22:57:01.536063+00:00'
[2024-04-21T22:57:02.656+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvju0jq3wp --system-site-packages --python=python
[2024-04-21T22:57:02.666+0000] {process_utils.py:186} INFO - Output:
[2024-04-21T22:57:03.451+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 403ms
[2024-04-21T22:57:03.452+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvju0jq3wp, clear=False, no_vcs_ignore=False, global=True)
[2024-04-21T22:57:03.452+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-04-21T22:57:03.452+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-04-21T22:57:03.453+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-04-21T22:57:03.484+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvju0jq3wp/bin/pip install -r /tmp/venvju0jq3wp/requirements.txt
[2024-04-21T22:57:03.489+0000] {process_utils.py:186} INFO - Output:
[2024-04-21T22:57:04.880+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.6.0 (from -r /tmp/venvju0jq3wp/requirements.txt (line 1))
[2024-04-21T22:57:04.987+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.6.0-py3-none-any.whl.metadata (23 kB)
[2024-04-21T22:57:05.155+0000] {process_utils.py:190} INFO - Collecting ucimlrepo==0.0.3 (from -r /tmp/venvju0jq3wp/requirements.txt (line 2))
[2024-04-21T22:57:05.181+0000] {process_utils.py:190} INFO -   Downloading ucimlrepo-0.0.3-py3-none-any.whl.metadata (5.2 kB)
[2024-04-21T22:57:05.226+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvju0jq3wp/requirements.txt (line 1)) (1.34.88)
[2024-04-21T22:57:05.227+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvju0jq3wp/requirements.txt (line 1)) (1.34.88)
[2024-04-21T22:57:05.229+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvju0jq3wp/requirements.txt (line 1)) (1.24.4)
[2024-04-21T22:57:05.229+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvju0jq3wp/requirements.txt (line 1)) (23.2)
[2024-04-21T22:57:05.231+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvju0jq3wp/requirements.txt (line 1)) (2.0.3)
[2024-04-21T22:57:05.232+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=7.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvju0jq3wp/requirements.txt (line 1)) (14.0.2)
[2024-04-21T22:57:05.233+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvju0jq3wp/requirements.txt (line 1)) (4.9.0)
[2024-04-21T22:57:05.240+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venvju0jq3wp/requirements.txt (line 1)) (0.10.0)
[2024-04-21T22:57:05.242+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venvju0jq3wp/requirements.txt (line 1)) (0.10.1)
[2024-04-21T22:57:05.247+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvju0jq3wp/requirements.txt (line 1)) (2.8.2)
[2024-04-21T22:57:05.248+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvju0jq3wp/requirements.txt (line 1)) (1.26.18)
[2024-04-21T22:57:05.329+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venvju0jq3wp/requirements.txt (line 1)) (2023.3.post1)
[2024-04-21T22:57:05.330+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venvju0jq3wp/requirements.txt (line 1)) (2023.4)
[2024-04-21T22:57:05.338+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvju0jq3wp/requirements.txt (line 1)) (1.16.0)
[2024-04-21T22:57:05.399+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.6.0-py3-none-any.whl (403 kB)
[2024-04-21T22:57:05.539+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 403.8/403.8 kB 2.9 MB/s eta 0:00:00
[2024-04-21T22:57:05.574+0000] {process_utils.py:190} INFO - Downloading ucimlrepo-0.0.3-py3-none-any.whl (7.0 kB)
[2024-04-21T22:57:08.389+0000] {process_utils.py:190} INFO - Installing collected packages: ucimlrepo, awswrangler
[2024-04-21T22:57:08.580+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.6.0 ucimlrepo-0.0.3
[2024-04-21T22:57:08.729+0000] {process_utils.py:190} INFO - 
[2024-04-21T22:57:08.730+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.0
[2024-04-21T22:57:08.730+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-04-21T22:57:09.033+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvju0jq3wp/bin/python /tmp/venv-callabsq9baw/script.py /tmp/venv-callabsq9baw/script.in /tmp/venv-callabsq9baw/script.out /tmp/venv-callabsq9baw/string_args.txt /tmp/venv-callabsq9baw/termination.log
[2024-04-21T22:57:09.041+0000] {process_utils.py:186} INFO - Output:
[2024-04-21T22:57:12.676+0000] {process_utils.py:190} INFO - [[34m2024-04-21T22:57:12.675+0000[0m] {[34mcredentials.py:[0m1147} INFO[0m - Found credentials in environment variables.[0m
[2024-04-21T22:57:12.736+0000] {process_utils.py:190} INFO - [[34m2024-04-21T22:57:12.736+0000[0m] {[34mconfigprovider.py:[0m957} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2024-04-21T22:57:13.051+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-04-21T22:57:13.060+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_heart_data, task_id=obtain_original_data, execution_date=20240421T225701, start_date=20240421T225702, end_date=20240421T225713
[2024-04-21T22:57:13.110+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-21T22:57:13.127+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
