[2024-04-25T19:59:30.633+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_mnist_784_data.obtain_original_data manual__2024-04-25T19:59:29.608592+00:00 [queued]>
[2024-04-25T19:59:30.637+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_mnist_784_data.obtain_original_data manual__2024-04-25T19:59:29.608592+00:00 [queued]>
[2024-04-25T19:59:30.637+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-25T19:59:30.645+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): obtain_original_data> on 2024-04-25 19:59:29.608592+00:00
[2024-04-25T19:59:30.649+0000] {standard_task_runner.py:60} INFO - Started process 8321 to run task
[2024-04-25T19:59:30.652+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_mnist_784_data', 'obtain_original_data', 'manual__2024-04-25T19:59:29.608592+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/etl_process.py', '--cfg-path', '/tmp/tmpnz7bhamm']
[2024-04-25T19:59:30.653+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask obtain_original_data
[2024-04-25T19:59:30.686+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_mnist_784_data.obtain_original_data manual__2024-04-25T19:59:29.608592+00:00 [running]> on host fc2c8bd597e1
[2024-04-25T19:59:30.730+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Carlos Rodriguez' AIRFLOW_CTX_DAG_ID='process_etl_mnist_784_data' AIRFLOW_CTX_TASK_ID='obtain_original_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-25T19:59:29.608592+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-25T19:59:29.608592+00:00'
[2024-04-25T19:59:30.731+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv6e2b7j9f --system-site-packages --python=python
[2024-04-25T19:59:30.737+0000] {process_utils.py:186} INFO - Output:
[2024-04-25T19:59:31.581+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 433ms
[2024-04-25T19:59:31.582+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venv6e2b7j9f, clear=False, no_vcs_ignore=False, global=True)
[2024-04-25T19:59:31.583+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-04-25T19:59:31.583+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-04-25T19:59:31.583+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-04-25T19:59:31.612+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv6e2b7j9f/bin/pip install -r /tmp/venv6e2b7j9f/requirements.txt
[2024-04-25T19:59:31.617+0000] {process_utils.py:186} INFO - Output:
[2024-04-25T19:59:33.091+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.6.0 (from -r /tmp/venv6e2b7j9f/requirements.txt (line 1))
[2024-04-25T19:59:33.196+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.6.0-py3-none-any.whl.metadata (23 kB)
[2024-04-25T19:59:33.923+0000] {process_utils.py:190} INFO - Collecting ucimlrepo==0.0.3 (from -r /tmp/venv6e2b7j9f/requirements.txt (line 2))
[2024-04-25T19:59:33.947+0000] {process_utils.py:190} INFO -   Downloading ucimlrepo-0.0.3-py3-none-any.whl.metadata (5.2 kB)
[2024-04-25T19:59:33.998+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venv6e2b7j9f/requirements.txt (line 1)) (1.34.88)
[2024-04-25T19:59:33.999+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venv6e2b7j9f/requirements.txt (line 1)) (1.34.88)
[2024-04-25T19:59:34.000+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venv6e2b7j9f/requirements.txt (line 1)) (1.24.4)
[2024-04-25T19:59:34.001+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venv6e2b7j9f/requirements.txt (line 1)) (23.2)
[2024-04-25T19:59:34.002+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venv6e2b7j9f/requirements.txt (line 1)) (2.0.3)
[2024-04-25T19:59:34.003+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=7.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venv6e2b7j9f/requirements.txt (line 1)) (14.0.2)
[2024-04-25T19:59:34.003+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venv6e2b7j9f/requirements.txt (line 1)) (4.9.0)
[2024-04-25T19:59:34.009+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venv6e2b7j9f/requirements.txt (line 1)) (0.10.0)
[2024-04-25T19:59:34.010+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venv6e2b7j9f/requirements.txt (line 1)) (0.10.1)
[2024-04-25T19:59:34.017+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venv6e2b7j9f/requirements.txt (line 1)) (2.8.2)
[2024-04-25T19:59:34.019+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venv6e2b7j9f/requirements.txt (line 1)) (1.26.18)
[2024-04-25T19:59:34.099+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venv6e2b7j9f/requirements.txt (line 1)) (2023.3.post1)
[2024-04-25T19:59:34.100+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venv6e2b7j9f/requirements.txt (line 1)) (2023.4)
[2024-04-25T19:59:34.107+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venv6e2b7j9f/requirements.txt (line 1)) (1.16.0)
[2024-04-25T19:59:34.206+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.6.0-py3-none-any.whl (403 kB)
[2024-04-25T19:59:34.529+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 403.8/403.8 kB 1.3 MB/s eta 0:00:00
[2024-04-25T19:59:34.577+0000] {process_utils.py:190} INFO - Downloading ucimlrepo-0.0.3-py3-none-any.whl (7.0 kB)
[2024-04-25T19:59:36.962+0000] {process_utils.py:190} INFO - Installing collected packages: ucimlrepo, awswrangler
[2024-04-25T19:59:37.344+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.6.0 ucimlrepo-0.0.3
[2024-04-25T19:59:37.488+0000] {process_utils.py:190} INFO - 
[2024-04-25T19:59:37.489+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.0
[2024-04-25T19:59:37.489+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-04-25T19:59:37.654+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv6e2b7j9f/bin/python /tmp/venv-call6egdp6ez/script.py /tmp/venv-call6egdp6ez/script.in /tmp/venv-call6egdp6ez/script.out /tmp/venv-call6egdp6ez/string_args.txt /tmp/venv-call6egdp6ez/termination.log
[2024-04-25T19:59:37.659+0000] {process_utils.py:186} INFO - Output:
[2024-04-25T19:59:48.056+0000] {process_utils.py:190} INFO - /home/***/.local/lib/python3.8/site-packages/sklearn/datasets/_openml.py:1022 FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
[2024-04-25T20:00:15.568+0000] {process_utils.py:190} INFO - [[34m2024-04-25T20:00:15.567+0000[0m] {[34mcredentials.py:[0m1147} INFO[0m - Found credentials in environment variables.[0m
[2024-04-25T20:00:15.709+0000] {process_utils.py:190} INFO - [[34m2024-04-25T20:00:15.709+0000[0m] {[34mconfigprovider.py:[0m957} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2024-04-25T20:00:37.125+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-04-25T20:00:37.133+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_mnist_784_data, task_id=obtain_original_data, execution_date=20240425T195929, start_date=20240425T195930, end_date=20240425T200037
[2024-04-25T20:00:37.156+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-25T20:00:37.170+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
